version: "2"
services:
  rating_server:
    build: rating_server
    image: rating_server:v1.0
    container_name: rating_server
    entrypoint: gunicorn -b 0.0.0.0:5000 -w 4 rating_server:app
    ports:
      - "5000:5000"
    stdin_open: true 
    tty: true
    links:
      - redis
    volumes:
      - .:/opt/server
    depends_on:
      - redis
  sync_service:
    build: sync_service
    image: sync_service:v1.0
    container_name: sync_service
    entrypoint: python3 -m sync_service sync
    restart: always
    environment:
      - PYTHONIOENCODING=utf-8
    links:
      - redis
    volumes:
      - .:/opt/server
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis_data:/data
